name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go build -o lku-${{ github.ref_name }}_linux_amd64

      - name: Create checksums
        run: |
          shasum -a 256 *-${{ github.ref_name }}_*_* >| checksums.txt
          file *-${{ github.ref_name }}_*_* checksums.txt

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --repo "${{ github.repository }}" \
            --generate-notes

      - name: Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" \
            --repo "${{ github.repository }}" \
            *-${{ github.ref_name }}_*_* \
            checksums.txt
